name: Split Monorepo

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  provide_packages_json:
    # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
    # see https://stackoverflow.com/a/62953566/1348344
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v2

      # required for matrix of packages set
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: 7.4
            coverage: none

      - name: composer
        run: |
          curl -O "https://getcomposer.org/download/2.0.14/composer.phar"
          chmod a+x composer.phar
          php composer.phar install

      # get package json list
      -
        id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json --exclude-package storage --exclude-package storage-admin)"

    # this step is needed, so the output gets to the next defined job
    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo:
    needs: provide_packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    steps:
      -   uses: actions/checkout@v2

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Monorepo Split of ${{ matrix.package }}
        uses: VojtechBuba/monorepo-split-github-action@2.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package-directory: 'packages/${{ matrix.package }}'
          split-repository-organization: 'VojtechBuba'
          split-repository-name: '${{ matrix.package }}'
          user-name: "GitHub Action"
          user-email: "action@github.com"
          branch: "main"

      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Monorepo Tagged Split of ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@2.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package-directory: 'packages/${{ matrix.package }}'
          split-repository-organization: 'VojtechBuba'
          split-repository-name: '${{ matrix.package }}'
          user-name: "GitHub Action"
          user-email: "action@github.com"
          branch: "main"
